language: node_js

node_js:
    - 8
    - node
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
    - npm test
after_success:
  - npm install nyc
  - npm install coveralls
  - npm run coverage
  - npm run coveralls
   